apiVersion: v1
data:
  telegraf.conf: "[[outputs.influxdb]]\n  urls = [\"$INFLUXDB_URL\"]\n  database =
    \"$INFLUXDB_DB\"\n  username = \"$INFLUXDB_USER\"\n  password = \"$INFLUXDB_USER_PASSWORD\"\n
    \ \n[[inputs.mqtt_consumer]]\n  json_name_key = \"name\"\n  servers = [\"tcp://mosquitto:1883\"]\n
    \ qos = 0\n  connection_timeout = \"30s\"\n  topics = [\n    \"temperature\",\n
    \ ]\n  tag_keys = [\"sensor_name\"]\n  persistent_session = false\n  data_format
    = \"json\"\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-20T12:20:11Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:telegraf.conf: {}
    manager: kubectl-create
    operation: Update
    time: "2020-10-20T12:20:11Z"
  name: telegraf-config
  namespace: default
  resourceVersion: "29288"
  selfLink: /api/v1/namespaces/default/configmaps/telegraf-config
  uid: 545ea199-54c0-454c-8c79-e14cc7970d8c
